# Défini tes services
  # Défini le service `mysql`
    # Précise l'image que tu veux pull
    # Tu peux préciser la politique de rédémarrage du conteneur
    # Crée les variables d'environnement
    # Précise le mapping de ports
    # Précise sur quel volume seront persistées les données
  # Défini le service `spring-app`
    # Précise que le build s'effectue dans le contexte actuel (pour aller cherche le Dockerfile)
    # Précise le mapping de ports
    # Crée les variables d'environnement
    # Précise que ce service dépend du service précédent `mysql`
# Défini tes volumes